# Generated by Django 5.0 on 2023-12-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0)),
                ('change_price', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='images/curr/')),
            ],
        ),
    ]
