# Generated by Django 5.0 on 2023-12-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='symbols',
            field=models.CharField(default='NO', max_length=10),
        ),
    ]
